#!/usr/bin/env python3
from pathlib import Path
import argparse,json,shutil,tempfile
from handoff_common import *
def main():
 a=argparse.ArgumentParser();a.add_argument('spec');a.add_argument('--runtime',required=True);a.add_argument('--audit',required=True);a.add_argument('--output',required=True);x=a.parse_args();s=json.loads(Path(x.spec).read_text());td=tempfile.mkdtemp();r=Path(td)/s['handoff_name'];r.mkdir();shutil.copytree(x.runtime,r/'RUNTIME');shutil.copytree(x.audit,r/'AUDIT_OS');copy_tools(r/'tools')
 dump(r/'HANDOFF_IDENTITY.json',{'handoff_id':s['handoff_id'],'status':'ACTIVE','orchestration_os_version':'10.0.0','audit_os_version':'6.0.0','contract_generation':'v10','expected_output_name':s['expected_output_name']});dump(r/'TARGET_IDENTITY.json',s);dump(r/'SOURCE_INPUT_REGISTRY.json',{'inputs':s.get('inputs',[])});dump(r/'PROTECTED_SURFACE_BASELINE.json',{'files':[],'mode':'NEW_RESEARCH_NO_EXISTING_KNOWLEDGE_BASELINE'});dump(r/'REQUIRED_OUTPUTS_AND_ACCEPTANCE.json',{'required_outputs':[{'filename':s['expected_output_name'],'type':'candidate_zip'},{'filename':'CONSTRUCTION_REPORT.md','type':'report'},{'filename':'RETURN_REPORT.md','type':'report'}],'acceptance':['Gate0 exact identity','external stage review','candidate finalizer','return inventory','v10 admission','external Audit OS v6']});dump(r/'INDEPENDENCE_STATE_MACHINE.json',{'states':['GATE0','CONSTRUCT','STAGE_PRE_REVIEW','SEAL','RETURN','EXTERNAL_AUDIT','PROMOTION'],'child_stop_state':'RETURN','child_forbidden_states':['MERGE_READY','PRODUCTION_RELEASE'],'role_separation':['Research Builder != Stage Pre-review Auditor','Research Builder != Candidate Auditor']})
 (r/'ALLOWED_CHANGE_MATRIX.csv').write_text('path_pattern,permission,allowed_fields,notes\nOUTPUT/**,ALLOW,*,New research construction output\nRUNTIME/**,DENY,,Immutable runtime\nAUDIT_OS/**,DENY,,Immutable Audit\ntools/**,DENY,,Immutable handoff tools\n');dump(r/'GATE0_RESPONSE.json',{'status':'NOT_COMPLETED','researcher_id':'','researcher_session_id':'','working_directory':'','expected_output_name':s['expected_output_name'],'blocking_issues':[]});(r/'00_PASTE_THIS_PROMPT_FIRST.txt').write_text('Read 01_START_HERE.md. Complete GATE0_RESPONSE.json before research. Use source-first proof-carrying construction. Stop after exact return inventory; do not self-audit.\n');(r/'01_START_HERE.md').write_text('# v10 Research Handoff\n\nGate 0 is mandatory. Run `python tools/validate_handoff_package.py .` before work. Direct claims must be compiler-generated from externally pre-reviewed material clauses. Before return run return inventory and stop before external Audit.\n')
 dump(r/'PACKAGE_VALIDATION.json',{'status':'BUILDING'});entries=manifest(r);dump(r/'manifest.json',{'entries':entries});(r/'SHA256SUMS.txt').write_text(''.join(f"{q['sha256']}  {q['path']}\n" for q in entries));dump(r/'PACKAGE_VALIDATION.json',{'status':'PASS','contract_generation':'v10','files':len(entries),'tools_embedded':True});entries=manifest(r);dump(r/'manifest.json',{'entries':entries});(r/'SHA256SUMS.txt').write_text(''.join(f"{q['sha256']}  {q['path']}\n" for q in entries));zipone(r,Path(x.output));print(json.dumps({'status':'PASS','output':x.output,'sha256':sha(x.output)},indent=2))
if __name__=='__main__':main()
